version: "3.8"
services: 
  api:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    env_file: 
      - app/.prod.env
    ports: 
      - 80:80
    depends_on: 
    - db
  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file: 
    - app/.prod.env
    expose: 
      - 5432

volumes:
  postgres_data:
